### ISSUE TITLE
Set up Monodevelop add-in repo

### ISSUE THREAD

**Issue by jimbobbennett** [straighteight/SpecFlow-VS-Mac-Integration#1]
To release this extension on the marketplace we need it to be set up inside the Monodevelop add-in repo

**Comment by jimbobbennett** [comment]
@mikeyjones - I've created a project for it under my account on the repo. If you have an account can you send me your account name so I can add you to the project, if not can you create an account.

http://addins.monodevelop.com/

**Comment by jimbobbennett** [comment]
Project is http://addins.monodevelop.com/Project/Index/290

**Comment by mikeyjones** [comment]
Brill, I PM'd you on twitter my details
