### ISSUE TITLE
MonoDevelop addin dependency error

### ISSUE THREAD

**Issue by dmitrykorolevlighting** [straighteight/SpecFlow-VS-Mac-Integration#10]
I am trying to install SpecFlow addin 1.11.1.0 on MonoDevelop 7.5, but getting the following error. Rolling back to MonoDevelop 7.0 did not help. Do I need to do something special to make it work?

![monodevelop-specflow](https://user-images.githubusercontent.com/29861700/40123773-47286a8e-5927-11e8-8ee8-3b52104ef0d6.png)

**Comment by jimbobbennett** [comment]
Are you using mlnodevelop or Visual Studio for Mac? This add-in has only been tested with VS for Mac, hence the requirement on the Xamarin components.
