### ISSUE TITLE
Cannot Install Plugin verion 1.11.2.0 

### ISSUE THREAD

**Issue by ParagRaut** [straighteight/SpecFlow-VS-Mac-Integration#13]
It needs latest dependecies which are not even available with latest Vs for Mac

<img width="440" alt="screen shot 2018-09-11 at 8 46 43 pm" src="https://user-images.githubusercontent.com/16030809/45381102-a3db9000-b604-11e8-8112-5197e567b375.png">

**Comment by claudio252** [comment]
Following https://docs.microsoft.com/es-es/visualstudio/mac/update fixed this issue for me.

**Comment by ParagRaut** [comment]
Hi @claudio252 I agree but why would anyone in a normal scenario would want to upgrade VS via alpha or beta channel. I often face issues with stable version already

**Comment by cosminstirbu** [comment]
I have the same issue.

According to the last comment on this issue https://github.com/straighteight/SpecFlow-VS-Mac-Integration/issues/12 it seems that 1.11.2.0 should work with VS for Mac 7.6, but it doesn't :(.

**Comment by ParagRaut** [comment]
Yes, @cosminstirbu Finally I switched update channel to beta and installed vs/mono and everything 7.7 and then it installed, but I really don't like doing it this way :(
