### ISSUE TITLE
Support Visual Studio for Mac 2019

### ISSUE THREAD

**Issue by WilliamWishart** [straighteight/SpecFlow-VS-Mac-Integration#19]
Please add support for Visual Studio for Mac 2019.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/20622568/54877966-9443cc00-4e1d-11e9-8792-45b30e75da63.png">

**Comment by mfranc28** [comment]
Me too, I update to VS Mac 2019 and I need this tool.....so please be fast.

**Comment by mikeyjones** [comment]
I had a build running in VS 2019 yesterday, I plan on publishing it within the next few hours, I'll post on here once it up and close the ticket. 

I am working on supporting SpecFlow version 3, but there are several changes we need to make to get the projects supporting this, and plan on it being a VS2019 only feature once it's out

**Comment by mikeyjones** [comment]
We now have support for VS Mac 2019  and SpecFlow V3 Enjoy!
