### ISSUE TITLE
Support for Specflow V3

### ISSUE THREAD

**Issue by ParagRaut** [straighteight/SpecFlow-VS-Mac-Integration#20]
Please add support for Specflow V3 as it supports .Net core out of the box
Currently generated files are for Specflow V2.3 and Nunit by default for some reason

**Comment by mikeyjones** [comment]
We are looking into this, with all the .Net core changes that SpecFlow havfe done, thee is a lot to change, but we will hopefully have an update on progress soon

**Comment by mikeyjones** [comment]
We now have SpecFlow V3 support for Visual Studio Mac 2019, let me know if you find any bugs, I was able to create a .Net Core library with Nunit and add SpecFlow and get a spec to pass

**Comment by ParagRaut** [comment]
Hi Mike, now new plugin doesn’t install with current stable version of Vs 2019, required mono framework version is higher than what it has in stable version

**Comment by mikeyjones** [comment]
hmmm, I'm on the stable branch, and it installed fine for me, there was an update to VS 2019 yesterday which I installed, what version are you on?

**Comment by mikeyjones** [comment]
My versions are:

Visual Studio Community 2019 for Mac
Version 8.0.1 (build 1)
Installation UUID: d325b691-dfc8-4c7a-a84a-b3959bdc7e33
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

Mono Framework MDK
Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

NuGet
Version: 4.8.2.5835

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0-preview-27324-5
	2.2.3
	2.1.9
	2.1.8
SDK: /usr/local/share/dotnet/sdk/3.0.100-preview-010184/Sdks
SDK Versions:
	3.0.100-preview-010184
	2.2.105
	2.1.505
	2.1.504
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

**Comment by ParagRaut** [comment]
Hi Mikey,
My visual studio is not updating for some reason or do I able to now I get this as an error while installing plugin:

<img width="432" alt="Screenshot 2019-04-06 at 12 43 48" src="https://user-images.githubusercontent.com/16030809/55668611-8efa6e80-586c-11e9-9a6d-8f5ff3ad67f5.png">

**Comment by mikeyjones** [comment]
OK, I have just published it for version 8.0 as well as 8.0.1, can you refresh your repo and try again for me?

**Comment by ParagRaut** [comment]
The extension manager is not able to connect to any repo for some reason, I already raised an issue in VS for mac forum.
<img width="634" alt="Screenshot 2019-04-06 at 12 52 44" src="https://user-images.githubusercontent.com/16030809/55668740-2613f600-586e-11e9-949a-0e69b49641d9.png">

I have to try it with manual install

**Comment by mikeyjones** [comment]
I did put an mpack in releases, so you can use that for now, https://github.com/straighteight/SpecFlow-VS-Mac-Integration/releases/tag/1.11.3.0

**Comment by ParagRaut** [comment]
Same issue, I see that last build was 14 hours ago. are you sure you included changes in that build ?

**Comment by mikeyjones** [comment]
Definitely built for 8.0:

        <Addin id="::MonoDevelop.Core" version="8.0" />
        <Addin id="::MonoDevelop.Ide" version="8.0" />

It was built with Visual Studio 8.0.1, so that might be the issue, I thought it was because I attached the mpack to 8.0.1 in the addin repo when I published it. Frustratingly, I cannot downgrade my copy to 8.0 now.

I'm thinking about what we can do about this :/

**Comment by ParagRaut** [comment]
okay, I think I will build this mpack and then try to install

**Comment by mikeyjones** [comment]
Are you on the preview build of VS Mac, or did you download the officially released one that came out on Tuesday?

**Comment by ParagRaut** [comment]
official stable one

**Comment by mikeyjones** [comment]
It's pretty easy to build, you'll need the AddinMaker, in the Extensions/Extension Development session. 

Clone this repo and build it.

in terminal go to the directory where the VisualStudio.SpecFlow.dll is and run:

`/Applications/Visual\ Studio.app/Contents/MacOS/vstool setup pack VisualStudio.SpecFlow.dll

**Comment by ParagRaut** [comment]
Finally I built it and it's enabled now
![image](https://user-images.githubusercontent.com/16030809/55668977-cc152f80-5871-11e9-9b58-01f4ce84351e.png)

**Comment by mikeyjones** [comment]
Well done, thanks for all your effort!

 I'll try and make sure I do builds with each version of VS Mac next time, I hope it works well for you. We have started looking at some enhancements to make life easier which generating the steps, but both Jim and I are pretty busy with our normal lives at the moment, so it's slow progress.

**Comment by ParagRaut** [comment]
Yes that's great anyway, progress is progress :)
I will let you know if I find something which is not working, or bugs
