### ISSUE TITLE
The .feature file is not visible, only the generated feature.cs file

### ISSUE THREAD

**Issue by Cybrosys** [straighteight/SpecFlow-VS-Mac-Integration#22]
Hello,

It seems that my .feature files are not visible, I have to right-click the Solution and select Show All Files under the Display Options menu item in order for them to become visible.

When adding a new SpecFlow Feature file, it gets the tag `<Visible>False</Visible>` set, changing it to True does not have any effect.

Is this something that can be solved in the extension, so that .feature files are visible, or is this an issue with VS for Mac?

**Comment by Cybrosys** [comment]
There were some nuget packages that were interfering with the operation of SpecFlow.

**Comment by Mittchel** [comment]
@Cybrosys could you maybe explain how you fixed this? I am still having the same problem

**Comment by Cybrosys** [comment]
Hi @Mittchel ,

I see you've found the open issue as well. For me it works when I only have, for example, these package dependencies:
  ```
<ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="SpecFlow" Version="3.1.97" />
    <PackageReference Include="SpecFlow.NUnit" Version="3.1.97" />
  </ItemGroup>
```

But when you add this package, things break down, and that's described in more detail in the open issue.
```
<PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.0.*" />
```
