### ISSUE TITLE
Generated code uses deprecated NUnit library

### ISSUE THREAD

**Issue by cemsezer** [straighteight/SpecFlow-VS-Mac-Integration#9]
generated feature.cs currently uses TestFixtureSetUpAttribute and TestFixtureTearDownAttribute which are both deprecated. Templates need updating to reflect this change.

**Comment by FWJay** [comment]
this is a hack, but has no one fixed this yet? https://github.com/techtalk/SpecFlow/issues/974

**Comment by shreyasshenoy** [comment]
This has been fixed in Specflow 2.2.0 and above but this particular implementation uses 2.1.0.
We probably need a new build with updated libraries.
